-- ----------------------------
-- 添加框架默认用户
-- ----------------------------
INSERT INTO colorxx.base_user (user_id, dept_id, user_name, nick_name, email, phone, sex, password, status, login_ip, login_date, remark, del_flag, create_by, create_time, update_by, update_time) VALUES 
(1, 1, 'OneAdmin', '颜一', 'miracleren@gmail.com', '13888888888', '0', '$2a$10$E7bLX.w.Sw2D2JG94cF29eMueTkT5IFSQJifpJgZmJOOkMBTqcSOG', 0, '127.0.0.1', '2022-06-02 15:01:29', '初始管理员', 0, 'admin', sysdate(), 'OneAdmin', sysdate());
INSERT INTO colorxx.base_user (user_id, dept_id, user_name, nick_name, email, phone, sex, password, status, login_ip, login_date, remark, del_flag, create_by, create_time, update_by, update_time) VALUES 
(2, 1, 'ColorAdmin', '颜颜', 'miracleren@gmail.com', '13666666666', '1', '$2a$10$E7bLX.w.Sw2D2JG94cF29eMueTkT5IFSQJifpJgZmJOOkMBTqcSOG', 0, '127.0.0.1', '2022-06-02 15:01:29', '初始管理员', 0, 'admin', sysdate(), 'OneAdmin', sysdate());



-- ----------------------------
-- 添加默认菜单数据
-- ----------------------------
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (1, '系统管理', 0, 100, 'c', 'system', '/system', 0, 0, 'FileTrayFull', '', 0, 'admin', '2022-11-29 00:31:36', 'OneAdmin', '2023-11-30 16:48:50');
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (2, '用户管理', 1, 1, 'm', '/system/manage/base-user', '/system/user', 0, 0, 'IdCard', '', 0, 'admin', '2022-11-29 00:31:36', 'OneAdmin', '2023-09-07 10:27:38');
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (3, '部门管理', 1, 2, 'm', '/system/manage/base-dept', '/system/dept', 0, 0, 'Tree', '', 0, 'admin', '2022-11-29 00:31:36', 'OneAdmin', '2023-09-07 10:28:07');
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (4, '角色管理', 1, 3, 'm', '/system/manage/base-role', '/system/role', 0, 0, 'PersonAdd', '', 0, 'admin', '2023-07-20 00:49:47', 'OneAdmin', '2023-09-07 10:29:56');
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (5, '菜单管理', 1, 4, 'm', '/system/manage/base-menu', '/system/menu', 0, 0, 'List', '', 0, 'admin', '2023-07-20 00:49:54', 'OneAdmin', '2023-09-07 10:30:58');
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (6, '字典管理', 1, 5, 'm', '/system/manage/base-dict', '/system/dict', 0, 0, 'Book', '', 0, 'admin', '2023-08-01 14:23:32', 'admin', '2023-08-01 14:23:32');
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (15, '新增字典数据', 6, 0, 'b', null, 'dict:add', 1, 0, '#', null, 0, 'OneAdmin', '2023-08-24 11:40:10', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (16, '查询字典数据列表', 6, 0, 'b', null, 'dict:list', 1, 0, '#', null, 0, 'OneAdmin', '2023-08-24 11:40:10', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (17, '查询子字典数据列表', 6, 0, 'b', null, 'dict:children:dictId', 1, 0, '#', null, 0, 'OneAdmin', '2023-08-24 11:40:10', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (18, '根据字典类型获取字典数据', 6, 0, 'b', null, 'dict:select:type', 1, 0, '#', null, 0, 'OneAdmin', '2023-08-24 11:40:10', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (19, '查询字典树数据', 6, 0, 'b', null, 'dict:tree', 1, 0, '#', null, 0, 'OneAdmin', '2023-08-24 11:40:10', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (20, '删除字典数据', 6, 0, 'b', null, 'dict:delete:dictId', 1, 0, '#', null, 0, 'OneAdmin', '2023-08-24 11:40:10', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (21, '修改字典数据', 6, 0, 'b', null, 'dict:edit', 1, 0, '#', null, 0, 'OneAdmin', '2023-08-24 11:40:10', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (28, '查询菜单数据列表', 5, 0, 'b', null, 'menu:list', 1, 0, '#', null, 0, 'OneAdmin', '2023-08-24 11:47:48', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (29, '新增菜单数据', 5, 0, 'b', null, 'menu:add', 1, 0, '#', null, 0, 'OneAdmin', '2023-08-24 11:47:48', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (30, '新增菜单操作接口', 5, 0, 'b', null, 'menu:permit:add', 1, 0, '#', null, 0, 'OneAdmin', '2023-08-24 11:47:48', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (31, '删除菜单数据', 5, 0, 'b', null, 'menu:delete:menuId', 1, 0, '#', null, 0, 'OneAdmin', '2023-08-24 11:47:48', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (32, '修改菜单数据', 5, 0, 'b', null, 'menu:edit', 1, 0, '#', null, 0, 'OneAdmin', '2023-08-24 11:47:48', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (33, '获取系统操作权限接口列表', 5, 0, 'b', null, 'menu:permit:url', 1, 0, '#', null, 0, 'OneAdmin', '2023-08-24 11:47:48', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (34, '新增角色数据', 4, 0, 'b', null, 'role:add', 1, 0, '#', null, 0, 'OneAdmin', '2023-08-25 16:32:32', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (35, '查询角色数据列表', 4, 0, 'b', null, 'role:list', 1, 0, '#', null, 0, 'OneAdmin', '2023-08-25 16:32:32', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (36, '删除角色数据', 4, 0, 'b', null, 'role:delete:roleId', 1, 0, '#', null, 0, 'OneAdmin', '2023-08-25 16:32:32', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (37, '修改角色数据', 4, 0, 'b', null, 'role:edit', 1, 0, '#', null, 0, 'OneAdmin', '2023-08-25 16:32:32', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (38, '修改用户数据', 2, 0, 'b', null, 'user:edit', 1, 0, '#', null, 0, 'OneAdmin', '2023-09-06 11:01:05', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (39, '重置用户密码', 2, 0, 'b', null, 'user:reset:password', 1, 0, '#', null, 0, 'OneAdmin', '2023-09-06 11:01:05', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (40, '删除用户数据', 2, 0, 'b', null, 'user:delete:userId', 1, 0, '#', null, 0, 'OneAdmin', '2023-09-06 11:01:05', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (41, '查询用户数据列表', 2, 0, 'b', null, 'user:list', 1, 0, '#', null, 0, 'OneAdmin', '2023-09-06 11:01:05', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (42, '新增用户数据', 2, 0, 'b', null, 'user:add', 1, 0, '#', null, 0, 'OneAdmin', '2023-09-06 11:01:05', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (43, '切换用户账号状态', 2, 0, 'b', null, 'user:status:switch', 1, 0, '#', null, 0, 'OneAdmin', '2023-09-06 11:01:05', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (44, '新增部门数据', 3, 0, 'b', null, 'dept:add', 1, 0, '#', null, 0, 'OneAdmin', '2023-09-06 11:01:18', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (45, '删除部门数据', 3, 0, 'b', null, 'dept:delete:deptId', 1, 0, '#', null, 0, 'OneAdmin', '2023-09-06 11:01:18', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (46, '修改部门数据', 3, 0, 'b', null, 'dept:edit', 1, 0, '#', null, 0, 'OneAdmin', '2023-09-06 11:01:18', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (47, '查询部门数据列表', 3, 0, 'b', null, 'dept:list', 1, 0, '#', null, 0, 'OneAdmin', '2023-09-06 11:01:18', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (48, '停用或启用部门', 3, 0, 'b', null, 'dept:set:status', 1, 0, '#', null, 0, 'OneAdmin', '2023-09-06 11:01:19', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (49, '首页', 0, 0, 'm', '/frame/dashboard', '/index', 0, 0, 'Apps', null, 0, 'OneAdmin', '2023-09-07 15:16:28', 'OneAdmin', '2023-09-07 11:14:56');
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (50, '公告管理', 1, 6, 'm', '/system/manage/base-notice', '/system/notice', 0, 0, 'ChatboxEllipses', null, 0, 'OneAdmin', '2023-09-26 00:02:39', 'OneAdmin', '2023-09-25 16:03:07');
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (51, '系统监控', 0, 101, 'c', 'monitor', '/monitor', 0, 0, 'BugSharp', null, 0, 'OneAdmin', '2023-11-30 16:50:19', '', null);
INSERT INTO colorxx.base_menu (menu_id, menu_name, parent_id, order_num, menu_type, component, path, visible, status, icon, remark, del_flag, create_by, create_time, update_by, update_time) VALUES (52, '登录日志', 51, 1, 'm', '/system/monitor/log-login', '/monitor/log/login', 0, 0, 'IdCard', null, 0, 'OneAdmin', '2023-11-30 16:53:41', 'OneAdmin', '2023-11-30 16:55:04');



-- ----------------------------
-- 添加默认角色数据
-- ----------------------------
INSERT INTO colorxx.base_role (role_id, role_name, role_key, role_sort, status, remark, del_flag, create_by, create_time, update_by, update_time, scope) VALUES (1, '系统超级管理员', 'A', 1, 0, '系统超级管理员角色', 0, 'OneAdmin', '2023-06-29 15:42:15', 'OneAdmin', '2023-09-14 10:22:34', '');
INSERT INTO colorxx.base_role (role_id, role_name, role_key, role_sort, status, remark, del_flag, create_by, create_time, update_by, update_time, scope) VALUES (2, '普通角色', 'general', 2, 0, '就是普通角色', 0, 'OneAdmin', '2023-08-24 16:40:31', 'OneAdmin', '2023-09-14 17:13:45', 'dept_id in ({dept.children}) or dept_id = {user.deptId}');

INSERT INTO colorxx.base_user_role (user_id, role_id, del_flag, create_by, create_time, update_by, update_time) VALUES (1, 1, 0, 'OneAdmin', '2023-06-29 15:46:32', '', null);
INSERT INTO colorxx.base_user_role (user_id, role_id, del_flag, create_by, create_time, update_by, update_time) VALUES (2, 1, 0, 'OneAdmin', '2023-09-06 10:52:07', '', null);


-- ----------------------------
-- 添加字典数据表
-- ----------------------------
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (1, null, 'base_user_status', '用户帐号状态', '', 1, '', 0, 0, 'admin', '2023-08-03 16:22:28', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (2, 1, 'base_user_status', '正常', '0', 1, '', 0, 0, 'admin', '2023-08-03 16:22:28', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (3, 1, 'base_user_status', '停用', '1', 2, '', 0, 0, 'admin', '2023-08-03 16:22:28', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (4, null, 'base_menu_type', '菜单类型', '', 2, '', 0, 0, 'admin', '2023-08-04 00:22:28', 'OneAdmin', '2023-08-29 10:48:21', null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (5, 4, 'base_menu_type', '目录', 'c', 1, '', 0, 0, 'admin', '2023-08-03 16:22:28', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (6, 4, 'base_menu_type', '菜单', 'm', 1, '', 0, 0, 'admin', '2023-08-03 16:22:28', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (7, 4, 'base_menu_type', '操作', 'b', 1, '', 0, 0, 'admin', '2023-08-03 16:22:28', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (9, null, 'base_status', '通用状态', '', 1, '', 0, 0, 'admin', '2023-08-03 16:22:28', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (10, 9, 'base_status', '正常', '0', 1, '', 0, 0, 'admin', '2023-08-03 16:22:28', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (11, 9, 'base_status', '停用', '1', 2, '', 0, 0, 'admin', '2023-08-03 16:22:28', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (33, 32, 'a', '2', '', 2, '', 0, 0, 'OneAdmin', '2023-08-14 15:18:55', '', null, '2');
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (45, null, 'base_visible', '通用显示状态', '', 4, '', 0, 0, 'OneAdmin', '2023-08-17 14:36:14', 'OneAdmin', '2023-08-17 14:53:54', null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (46, 45, 'base_visible', '显示', '0', 1, '', 0, 0, 'OneAdmin', '2023-08-17 14:36:34', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (47, 45, 'base_visible', '隐藏', '1', 2, '', 0, 0, 'OneAdmin', '2023-08-17 14:36:58', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (48, null, 'base_user_sex', '用户性别', '', 10, '', 0, 0, 'OneAdmin', '2023-08-28 15:40:24', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (49, 48, 'base_user_sex', '男', '0', 1, '', 0, 0, 'OneAdmin', '2023-08-28 15:40:41', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (50, 48, 'base_user_sex', '女', '1', 2, '', 0, 0, 'OneAdmin', '2023-08-28 15:41:18', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (51, 48, 'base_user_sex', '其他', '2', 3, '', 0, 0, 'OneAdmin', '2023-08-28 15:44:25', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (82, null, 'role_data_scope', '角色数据权限', '', 1, '', 0, 0, 'OneAdmin', '2023-09-12 10:10:35', '', null, '角色数据权限配置');
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (84, 82, 'role_data_scope', '本人', 'user_name = {user.userName}', 1, '', 0, 0, 'OneAdmin', '2023-09-12 22:06:16', 'OneAdmin', '2023-09-14 10:22:08', null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (85, 82, 'role_data_scope', '本部门', 'dept_id = {user.deptId}', 2, '', 0, 0, 'OneAdmin', '2023-09-12 22:07:23', 'OneAdmin', '2023-09-14 10:22:21', null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (86, 82, 'role_data_scope', '子部门', 'dept_id in ({dept.children})', 3, '', 0, 0, 'OneAdmin', '2023-09-13 06:08:42', 'OneAdmin', '2023-09-12 14:14:24', null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (87, 82, 'role_data_scope', '父部门	', 'dept_id in ({dept.ancestors})', 4, '', 0, 0, 'OneAdmin', '2023-09-12 14:15:35', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (88, 82, 'role_data_scope', '所有数据', '1 = 1', 4, '', 0, 0, 'OneAdmin', '2023-09-12 22:17:42', 'OneAdmin', '2023-09-12 14:17:49', null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (89, null, 'base_notice_type', '公告类型', '', 11, '', 0, 0, 'OneAdmin', '2023-09-25 15:57:37', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (90, 89, 'base_notice_type', '通知', '1', 1, '', 0, 0, 'OneAdmin', '2023-09-25 15:58:50', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (91, 89, 'base_notice_type', '公告', '2', 2, '', 0, 0, 'OneAdmin', '2023-09-25 15:59:04', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (92, null, 'base_notice_files', '公告附件文件类别', '', 10, '', 0, 0, 'OneAdmin', '2023-10-31 15:21:52', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (93, 92, 'base_notice_files', '公告原件', '1', 1, '', 0, 0, 'OneAdmin', '2023-10-31 15:24:54', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (94, 92, 'base_notice_files', '法律文件', '2', 2, '', 0, 0, 'OneAdmin', '2023-10-31 15:25:32', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (95, 92, 'base_notice_files', '执行文件', '3', 3, '', 0, 0, 'OneAdmin', '2023-10-31 15:25:54', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (96, null, 'base_success_status', '通用成功状态', '', 12, '', 0, 0, 'OneAdmin', '2023-11-30 17:00:06', 'OneAdmin', '2023-11-30 17:03:00', null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (97, 96, 'base_success_status', '成功', '0', 1, '', 0, 0, 'OneAdmin', '2023-11-30 17:03:17', '', null, null);
INSERT INTO colorxx.base_dict (dict_id, parent_id, dict_type, dict_label, dict_value, dict_sort, style, status, del_flag, create_by, create_time, update_by, update_time, remark) VALUES (98, 96, 'base_success_status', '失败', '1', 2, '', 0, 0, 'OneAdmin', '2023-11-30 17:03:29', '', null, null);


-- ----------------------------
-- 添加部门数据表
-- ----------------------------
INSERT INTO colorxx.base_dept (dept_id, parent_id, dept_name, leader, contact, dept_sort, status, remark, del_flag, create_by, create_time, update_by, update_time, ancestors) VALUES (1, null, '非人类研究所', '李先生', '卫星', 0, 0, '无', 0, '', '2023-08-31 11:17:09', '', null, '');
INSERT INTO colorxx.base_dept (dept_id, parent_id, dept_name, leader, contact, dept_sort, status, remark, del_flag, create_by, create_time, update_by, update_time, ancestors) VALUES (2, 1, '通信部', '陈先生', null, 1, 0, '无', 0, '', '2023-08-31 11:17:11', '', null, '1');
INSERT INTO colorxx.base_dept (dept_id, parent_id, dept_name, leader, contact, dept_sort, status, remark, del_flag, create_by, create_time, update_by, update_time, ancestors) VALUES (3, 1, '解剖部', '何先生', null, 2, 0, '无', 0, '', '2023-08-31 11:17:12', '', null, '1');
INSERT INTO colorxx.base_dept (dept_id, parent_id, dept_name, leader, contact, dept_sort, status, remark, del_flag, create_by, create_time, update_by, update_time, ancestors) VALUES (4, 2, '无线电通信', null, null, 1, 1, null, 0, 'OneAdmin', '2023-08-31 13:59:45', 'OneAdmin', '2023-08-31 15:30:26', '1,2');
INSERT INTO colorxx.base_dept (dept_id, parent_id, dept_name, leader, contact, dept_sort, status, remark, del_flag, create_by, create_time, update_by, update_time, ancestors) VALUES (5, 2, '量子通信', '何先生', '无', 2, 0, null, 0, 'OneAdmin', '2023-08-31 22:00:02', 'OneAdmin', '2023-08-31 14:44:27', '1,2');
INSERT INTO colorxx.base_dept (dept_id, parent_id, dept_name, leader, contact, dept_sort, status, remark, del_flag, create_by, create_time, update_by, update_time, ancestors) VALUES (6, 3, '科室A', null, null, 1, 0, null, 0, 'OneAdmin', '2023-09-06 10:41:58', '', null, '1,3');
INSERT INTO colorxx.base_dept (dept_id, parent_id, dept_name, leader, contact, dept_sort, status, remark, del_flag, create_by, create_time, update_by, update_time, ancestors) VALUES (7, 3, '科室B', null, null, 2, 0, null, 0, 'OneAdmin', '2023-09-06 10:42:12', '', null, '1,3');
INSERT INTO colorxx.base_dept (dept_id, parent_id, dept_name, leader, contact, dept_sort, status, remark, del_flag, create_by, create_time, update_by, update_time, ancestors) VALUES (8, 1, '学习部', null, null, 4, 0, null, 0, 'OneAdmin', '2023-09-06 10:43:27', '', null, '1');
INSERT INTO colorxx.base_dept (dept_id, parent_id, dept_name, leader, contact, dept_sort, status, remark, del_flag, create_by, create_time, update_by, update_time, ancestors) VALUES (11, 5, '量子密码科', null, null, 1, 0, null, 0, 'OneAdmin', '2023-09-14 10:17:38', '', null, '1,2,1001');
INSERT INTO colorxx.base_dept (dept_id, parent_id, dept_name, leader, contact, dept_sort, status, remark, del_flag, create_by, create_time, update_by, update_time, ancestors) VALUES (12, 5, '量子传输科', null, null, 1, 0, null, 0, 'OneAdmin', '2023-09-14 10:18:10', '', null, '1,2,1001');

-- ----------------------------
-- 添加公告数据表
-- ----------------------------
INSERT INTO colorxx.base_notice (notice_id, notice_title, notice_type, notice_content, start_date, end_date, del_flag, create_by, create_time, update_by, update_time) VALUES (1, '颜一系统发布', '1', '颜一系统发布了，欢迎你使用！', '2023-09-01 16:17:01', '2024-09-01 16:17:32', 0, 'OneAdmin', '2023-09-25 16:45:43', 'OneAdmin', '2023-09-26 14:28:34');
